apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sigstore-demo-app
  labels:
    app: sigstore-demo-app
spec:
  host: sigstore-demo-app.apps.sigstore-demo.bcallawa.dev # Modify to use your FQDN e.g. <app-name>.apps.<clustername>.<domain>.
  tls:
    termination: edge # Relies on OpenShift setup with Let's Encrypt.
  to:
    kind: Service
    name: sigstore-demo-app
